apiVersion: skaffold/v4beta6
kind: Config

build:
  artifacts:
    - image: frontend
      context: frontend
      sync:
        infer:
          - '**/*'

    - image: product-control-plane
      context: product-control-plane
      sync:
        infer:
          - '**/*'

    - image: infra-control-plane
      context: infra-control-plane
      sync:
        infer:
          - '**/*'

    - image: agent-runtime
      context: agent-runtime
      sync:
        manual:
          - src: '**/*.py'
            dest: /app

    - image: test-job
      context: test-job
      sync:
        manual:
          - src: '**/*.py'
            dest: /app

manifests:
  rawYaml:
    - k8s/namespaces.yaml
    - k8s/test-job.yaml
  kustomize:
    paths:
      - k8s/overlays/dev

profiles:
  - name: prod
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod
