apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: agent-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend
          imagePullPolicy: IfNotPresent
          command: ['npm', 'run', 'dev']
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_PRODUCT_API
              value: 'http://product-control-plane:3000'
            # These 5 values are for hot module reloading
            - name: WATCHPACK_POLLING
              value: 'true'
            - name: WATCHPACK_POLLING_INTERVAL
              value: '100'
            - name: CHOKIDAR_USEPOLLING
              value: 'true'
            - name: CHOKIDAR_INTERVAL
              value: '100'
            - name: WATCHPACK_FORCE_POLLING
              value: 'true'

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: agent-platform
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
