import './globals.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { Navbar, Footer } from '../components'
import { ThemeProvider } from '@/components/theme-provider'
import { DesignSystemProvider } from '@/providers/design-system'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'AI Agent Marketplace',
  description: 'Generated by AI Agent Marketplace',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          enableSystem
          attribute='class'
          defaultTheme='system'
          disableTransitionOnChange
        >
          <DesignSystemProvider>
            <Navbar />
            {children}
            <Footer />
          </DesignSystemProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
